version: "3.8"

networks:
  default:
    name: nb-tests

services:
  server:
    image: 'nginx:stable-alpine'
    container_name: 'nginx_server'
    ports:
      - '80:80'
    volumes:
      - './conf/default.conf:/etc/nginx/conf.d/default.conf'
      - './src:/var/www/nb'
  php:
    container_name: 'php'
    build:
      context: .
      dockerfile: './php/php.dockerfile'
    volumes:
      - './src:/var/www/nb'
  mysqldb:
    container_name: 'mysql'
    image: 'mysql:8.0'
    restart: always
    env_file:
      - './db/.env.db'
    ports:
      - '43306:3306'
    volumes:
      - 'database-data:/var/lib/mysql'
  redis:
    container_name: 'redis'
    image: "redis:latest"
    ports:
      - "6379:6379"
volumes:
  database-data:
    driver: local